### ISSUE TITLE
Update to Meteor 1.2 breaks package.

### ISSUE THREAD

**Issue by chasemb** [englue/meteor-bootstrap3-sass#28]
I receive the following error that cannot be fixed with a restart.

    While processing files with fourseven:scss (for target web.browser):
    /client/styles/style.scss: Scss compiler error: File to import:
    .meteor/local/build/programs/server/assets/packages/reywood_bootstrap3-sass/bootstrap
    not found. Import origin: /client/styles/style.scss

**Comment by MikeSmith12222** [comment]
just ran into the same problem

**Comment by reywood** [comment]
Fixed in newest release. Note that the import statement has changed. Update your SCSS files to use:

```scss
@import '{reywood:bootstrap3-sass}/bootstrap';
```

**Comment by dyaa** [comment]
@reywood  What if i want import let's say mixins.scss only ? I was doing it with

    @import ".meteor/local/build/programs/server/assets/packages/reywood_bootstrap3-sass/assets/stylesheets/bootstrap/mixins";

but now the file is not found.

**Comment by reywood** [comment]
In that case, you would use:

```scss
@import '{reywood:bootstrap3-sass}/assets/stylesheets/bootstrap/mixins';
```
